name: Build

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build shared libraries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash -euxo pipefail {0}
    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: |
          curl -sLv --retry 5 https://nginx.org/download/nginx-1.21.3.tar.gz | gunzip | tar -x
          git clone https://github.com/vision5/ngx_devel_kit.git

      - name: Run test
        run: |
          pushd modules/ngx_http_cbor_ic_modules
          make NGINX_SRC=nginx-1.21.3
          popd

      - name: Build module so file
        run: |
          cd nginx-1.21.3
          ./configure --with-compat \
            --add-dynamic-module=../ngx_devel_kit \
            --add-dynamic-module=../modules/ngx_http_cbor_input_module \
            --add-dynamic-module=../modules/ngx_http_cbor_ic_modules
          make modules
